import { PrismaClient, FeedCategory, FeedType, FeedAudience } from '@prisma/client';

export async function seedContent(prisma: PrismaClient) {
    console.log('\n📰 Seeding Career Discovery Feed (Static Content)...');

    await prisma.feedItem.deleteMany({});

    const agencyUserId = '097944c2-3582-4220-ade4-4a93ab404375';
    const candidateUserId = '5900ca1a-625c-4a14-8331-ee286900ad73';

    // Helper function to create an item with random timestamp in the last 60 days
    async function createItem(baseItem: any) {
        const daysBack = Math.floor(Math.random() * 60);
        const hoursOffset = Math.floor(Math.random() * 24);
        const minutesOffset = Math.floor(Math.random() * 60);
        const createdAt = new Date();
        createdAt.setDate(createdAt.getDate() - daysBack);
        createdAt.setHours(hoursOffset);
        createdAt.setMinutes(minutesOffset);

        return prisma.feedItem.create({
            data: {
                ...baseItem,
                createdAt,
            },
        });
    }

    // --- LEARN_GROW (20 items) ---
    const learnGrowItems = [
        // Original 10
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "How to Build a Killer Portfolio Website That Stands Out",
            content: "In today's competitive job market, your portfolio is your digital handshake. This comprehensive guide walks you through selecting the right tech stack (React or vanilla HTML/CSS/JS), designing a clean UI, and integrating interactive elements like project demos and testimonials. Includes code snippets and free templates to get you started in under a weekend.",
            link: "https://ppalink.com/blog/portfolio-guide",
            ctaText: "Build Yours Now",
            imageUrl: "https://example.com/images/portfolio-website.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.WEBINAR,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "Free Webinar: CV Writing Masterclass with a Top Recruiter",
            content: "Tired of your CV getting lost in the ATS black hole? Join Chioma Okonjo, a 10-year recruiter at Andela, for a live 90-minute session. Learn keyword optimization, quantifiable achievements, and tailoring your CV for Nigerian tech roles. Q&A included, plus a free CV template download.",
            link: "https://ppalink.com/events/cv-masterclass",
            ctaText: "Register for Free",
            imageUrl: "https://example.com/images/cv-webinar.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "The 10 Most In-Demand Tech Skills in Nigeria for 2025 and How to Learn Them",
            content: "From AI/ML to cybersecurity, our analysis of 5,000+ job postings reveals the skills exploding in demand. For each skill, we provide free resources, estimated learning time (e.g., 40 hours for Python basics), and certification paths like Google Data Analytics or AWS Cloud Practitioner.",
            link: "https://ppalink.com/blog/in-demand-skills-2025",
            ctaText: "Start Learning",
            imageUrl: "https://example.com/images/tech-skills-2025.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.EVENT,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "PPALink Virtual Career Fair: Connect with 50+ Employers",
            content: "Mark your calendar for November 15th! Network via video booths, attend live workshops on interview prep and salary negotiation, and apply to roles on the spot. Past attendees landed interviews at Flutterwave and Interswitch. Free entry for verified PPALink users.",
            link: "https://ppalink.com/events/virtual-fair",
            ctaText: "RSVP Today",
            imageUrl: "https://example.com/images/career-fair.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "A Complete Guide to Answering 'Tell Me About Yourself' in Interviews",
            content: "This isn't just small talk—it's your 60-second elevator pitch. We break it down: Structure (past, present, future), common pitfalls (e.g., reciting your CV), and examples tailored for fresh grads vs. experienced pros. Practice with our interactive script builder.",
            link: "https://ppalink.com/blog/tell-me-about-yourself",
            ctaText: "Practice Now",
            imageUrl: "https://example.com/images/interview-guide.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.WEBINAR,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "Live Q&A: Navigating the Nigerian Tech Scene with Industry Veterans",
            content: "Got questions on breaking into FinTech, remote work visas, or upskilling during NYSC? Our panel— including a Paystack engineer and a GTBank product manager—will answer live. Submit questions in advance for priority responses. Replay available for 7 days.",
            link: "https://ppalink.com/events/tech-qa",
            ctaText: "Join the Live Session",
            imageUrl: "https://example.com/images/tech-qa-panel.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "How to Leverage LinkedIn to Land Your Dream Job in Nigeria",
            content: "With 70% of Nigerian recruiters using LinkedIn, your profile needs to shine. Tips include optimizing your headline (beyond 'Job Seeker'), building connections with alumni, and using Sales Navigator for job alerts. Case study: How one user got 3 interviews in a week.",
            link: "https://ppalink.com/blog/linkedin-strategy",
            ctaText: "Optimize Profile",
            imageUrl: "https://example.com/images/linkedin-tips.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "Demystifying Stock Options and Equity in Nigerian Startups",
            content: "Equity sounds great, but what does it really mean? We explain vesting schedules, dilution risks, and tax implications under Nigerian law. Includes a calculator to estimate your potential payout and real stories from PiggyVest and Kuda employees.",
            link: "https://ppalink.com/blog/equity-guide",
            ctaText: "Calculate Yours",
            imageUrl: "https://example.com/images/stock-options.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.WEBINAR,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "Public Speaking for Young Professionals: Build Confidence on Stage",
            content: "From pitch decks to client meetings, communication is key. This 2-hour workshop covers body language, storytelling techniques, and handling Q&A. Led by a TEDx speaker; includes peer practice sessions and feedback. Certificate of completion provided.",
            link: "https://ppalink.com/events/public-speaking",
            ctaText: "Enroll Today",
            imageUrl: "https://example.com/images/public-speaking.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "Salary Negotiation for Graduates: Don't Undersell Yourself",
            content: "Research shows 60% of grads accept the first offer. Learn counter-offer scripts, when to walk away, and non-salary perks like remote work or learning stipends. Backed by PPALink salary data from 10,000+ roles, with examples for ₦200k-₦500k ranges.",
            link: "https://ppalink.com/blog/salary-negotiation",
            ctaText: "Negotiate Smarter",
            imageUrl: "https://example.com/images/salary-negotiation.jpg",
            userId: agencyUserId,
        },
        // Additional 10
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "Mastering Git for Collaborative Coding in Teams",
            content: "Git isn't just version control—it's your collaboration superpower. From branching strategies to resolving merge conflicts, this guide equips you with practical commands and workflows used by teams at Google and GitHub. Includes a cheat sheet download.",
            link: "https://ppalink.com/blog/git-mastery",
            ctaText: "Download Cheat Sheet",
            imageUrl: "https://example.com/images/git-guide.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.WEBINAR,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "Intro to Data Analysis with Python: Hands-On Workshop",
            content: "No prior coding? No problem. In 2 hours, learn Pandas basics, data cleaning, and visualization with Matplotlib. Analyze a real Nigerian job market dataset. Led by a data scientist from Jumia; project files provided.",
            link: "https://ppalink.com/events/python-data",
            ctaText: "Join Workshop",
            imageUrl: "https://example.com/images/python-workshop.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "Building Your Personal Brand as a Freelance Developer",
            content: "Stand out on Upwork and Fiverr with a cohesive brand. Tips on niche selection, client testimonials, and pricing tiers. Case study: A Nigerian freelancer scaling to $5k/month in 6 months.",
            link: "https://ppalink.com/blog/personal-brand",
            ctaText: "Start Branding",
            imageUrl: "https://example.com/images/personal-brand.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.EVENT,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "Hackathon Prep: Strategies for Winning Prizes and Portfolios",
            content: "From ideation to demo day: Join mentors from CcHUB for a 4-week prep series. Focus on AI/ML themes relevant to Nigerian challenges like agriculture tech. Past winners share code repos.",
            link: "https://ppalink.com/events/hackathon-prep",
            ctaText: "Sign Up",
            imageUrl: "https://example.com/images/hackathon.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "Time Management Techniques for Bootcamp Students",
            content: "Juggling coding challenges and job hunts? Pomodoro, Eisenhower matrix, and Notion templates tailored for 12-week programs. Boost productivity by 40% with these proven methods.",
            link: "https://ppalink.com/blog/time-management",
            ctaText: "Try Templates",
            imageUrl: "https://example.com/images/time-mgmt.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.WEBINAR,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "Ethical Hacking Basics: Cybersecurity for Beginners",
            content: "Understand vulnerabilities without the jargon. Demo common attacks like SQL injection, plus defense tools like Wireshark. Ideal for entry-level security roles; cert prep included.",
            link: "https://ppalink.com/events/ethical-hacking",
            ctaText: "Watch Demo",
            imageUrl: "https://example.com/images/cybersecurity.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "Creating Reusable React Components: Best Practices",
            content: "Avoid prop drilling with hooks and context. Real-world examples from e-commerce apps. Includes a starter kit on GitHub for your next project.",
            link: "https://ppalink.com/blog/react-components",
            ctaText: "Fork Starter Kit",
            imageUrl: "https://example.com/images/react-components.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "Understanding Agile Methodologies for New Developers",
            content: "Scrum vs. Kanban: When to use each in Nigerian startups. Role-playing sprints and retrospectives to internalize the flow.",
            link: "https://ppalink.com/blog/agile-basics",
            ctaText: "Run a Sprint",
            imageUrl: "https://example.com/images/agile.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.WEBINAR,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "UI/UX Design Principles with Figma for Non-Designers",
            content: "Wireframing to prototypes: Hands-on session for devs transitioning to full-stack. Collaborate on a job board redesign; export assets for code.",
            link: "https://ppalink.com/events/figma-basics",
            ctaText: "Prototype Now",
            imageUrl: "https://example.com/images/figma-workshop.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.LEARN_GROW,
            audience: FeedAudience.CANDIDATE,
            title: "Debugging JavaScript: Tools and Techniques for Faster Fixes",
            content: "From console.log hell to Chrome DevTools mastery. Step-by-step on breakpoints, sourcemaps, and ESLint integration. Save hours on bug hunts.",
            link: "https://ppalink.com/blog/js-debugging",
            ctaText: "Debug Smarter",
            imageUrl: "https://example.com/images/debugging.jpg",
            userId: agencyUserId,
        },
    ];

    // --- CAREER_INSIGHT (20 items) ---
    const careerInsightItems = [
        // Original 10
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "Insight: Remote Work Trends Show 45% Growth in Nigerian Tech Jobs",
            content: "PPALink data from Q1-Q3 2025: Remote postings up 45%, with Lagos-Abuja hubs leading. Top remote skills? Full-stack dev and digital marketing. Pro tip: Highlight 'remote-ready' in your profile to boost visibility by 30%. Full report inside.",
            link: "https://ppalink.com/insights/remote-trends",
            ctaText: "Download Report",
            imageUrl: "https://example.com/images/remote-work-insight.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "Entry-Level Salary Breakdown: Lagos (₦350k) vs. Abuja (₦320k) vs. PH (₦300k)",
            content: "Based on 2,500 verified offers. Factors: Cost of living, industry (FinTech pays 20% more). See skill-wise breakdowns and negotiation tips to close the gap. Data updated monthly.",
            link: "https://ppalink.com/insights/salary-locations",
            ctaText: "View Full Data",
            imageUrl: "https://example.com/images/salary-breakdown.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "The Explosive Rise of Product Management Roles in Nigerian Tech",
            content: "PM jobs up 60% YoY, with entry-level at ₦400k avg. Why? Scaling startups need user-focused pros. Key skills: User research, A/B testing. Read interviews with PMs at Moniepoint and Opay.",
            link: "https://ppalink.com/blog/pm-rise-nigeria",
            ctaText: "Explore PM Roles",
            imageUrl: "https://example.com/images/product-management.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "Top 3 Hiring Industries on PPALink: FinTech, HealthTech, EdTech",
            content: "FinTech leads with 1,200 postings (35%), driven by remittances and payments. HealthTech surges post-COVID. See hottest roles like backend devs and product analysts, plus application success rates.",
            link: "https://ppalink.com/insights/top-industries",
            ctaText: "Filter by Industry",
            imageUrl: "https://example.com/images/hiring-industries.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "What 50 Top Recruiters Say About Ideal Candidate Profiles",
            content: "Our survey: 80% prioritize verified skills over degrees. Common advice: Quantify impacts (e.g., 'Boosted sales 25%'), keep CVs to 1 page. Includes recruiter quotes and profile audit checklist.",
            link: "https://ppalink.com/blog/recruiter-survey",
            ctaText: "Audit Your Profile",
            imageUrl: "https://example.com/images/recruiter-insights.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "Key Stat: Verified Profiles Get 2x More Offers (70% of Hires)",
            content: "From 15k applications: NYSC + skill verification = 2.1x hire rate. Why? Trust signal. Quick wins: Complete email verification (5 mins) and take one quiz. See before/after stats.",
            link: "https://ppalink.com/insights/verification-impact",
            ctaText: "Verify Now",
            imageUrl: "https://example.com/images/verified-profiles.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "Spotting Company Culture: 10 Red Flags and Green Flags in Interviews",
            content: "Red flags: High turnover mentions, vague values. Green: Inclusive language, work-life balance questions. Based on 200 candidate stories. Use our interview scorecard template.",
            link: "https://ppalink.com/blog/company-culture",
            ctaText: "Download Scorecard",
            imageUrl: "https://example.com/images/company-culture.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "Most Assessed Skill on PPALink: Project Management (Passed by 65%)",
            content: "PM quizzes taken 8k times this year. Boost your profile: Aim for 80%+ score. Correlates with 40% more shortlists. See top resources to prep.",
            link: "https://ppalink.com/insights/pm-assessments",
            ctaText: "Take PM Quiz",
            imageUrl: "https://example.com/images/project-mgmt.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "Why Soft Skills Trump Hard Tech Skills in Hybrid Teams",
            content: "Hiring managers rank communication #1 (85%). Tips: Use STAR method for behavioral questions, join Toastmasters. Case: How empathy landed a dev role at a remote-first startup.",
            link: "https://ppalink.com/blog/soft-skills-tech",
            ctaText: "Build Soft Skills",
            imageUrl: "https://example.com/images/soft-skills.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "Application Timing Hack: Mondays Get 25% Faster Responses",
            content: "Data from 50k apps: Mon 9-11 AM peak. Avoid Fridays. A/B test: Same CV, timed differently—results inside. Plus, email subject line tips for follow-ups.",
            link: "https://ppalink.com/insights/app-timing",
            ctaText: "Apply on Monday",
            imageUrl: "https://example.com/images/application-trends.jpg",
            userId: candidateUserId,
        },
        // Additional 10
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "Freelance Boom: 30% of Tech Roles Now Gig-Based in Nigeria",
            content: "Upwork data: Nigerian freelancers earned ₦2B in 2025. Top gigs: Web dev, graphic design. Risks and rewards analyzed, with portfolio tips for platforms.",
            link: "https://ppalink.com/insights/freelance-trends",
            ctaText: "Start Freelancing",
            imageUrl: "https://example.com/images/freelance-insight.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "The Impact of AI on Entry-Level Coding Jobs: Adapt or Pivot?",
            content: "AI tools like Copilot automate 20% of junior tasks. Focus on prompt engineering and ethics. Interviews with devs who upskilled successfully.",
            link: "https://ppalink.com/blog/ai-coding-jobs",
            ctaText: "Learn AI Tools",
            imageUrl: "https://example.com/images/ai-insight.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "Women in Tech: Representation Up 15%, But Glass Ceiling Persists",
            content: "From 12% to 27% in leadership. Barriers: Bias in promotions. Success stories and advocacy resources for female candidates.",
            link: "https://ppalink.com/insights/women-tech",
            ctaText: "Join Network",
            imageUrl: "https://example.com/images/women-tech.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "Burnout in Tech: Signs and Recovery Strategies for Nigerians",
            content: "60-hour weeks common in Lagos hubs. Self-care routines, boundary-setting, and when to job-hop. Survey of 1k pros.",
            link: "https://ppalink.com/blog/tech-burnout",
            ctaText: "Assess Burnout",
            imageUrl: "https://example.com/images/burnout.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "Gig Economy Shift: 40% Prefer Contracts Over Full-Time",
            content: "Flexibility vs. stability debate. Data on earnings variance and health insurance gaps in Nigerian context.",
            link: "https://ppalink.com/insights/gig-shift",
            ctaText: "Explore Gigs",
            imageUrl: "https://example.com/images/gig-economy.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "Mentorship's ROI: Mentees 2.5x More Likely to Get Promoted",
            content: "How to find mentors on PPALink. Structured programs vs. informal coffee chats. Real ROI calculations.",
            link: "https://ppalink.com/blog/mentorship-roi",
            ctaText: "Find a Mentor",
            imageUrl: "https://example.com/images/mentorship.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "Skill Gaps in Nigerian Hiring: Cloud Computing Tops List",
            content: "80% of jobs require AWS/Azure, but only 25% of candidates certified. Bridge the gap with free trials and paths.",
            link: "https://ppalink.com/insights/skill-gaps",
            ctaText: "Certify Now",
            imageUrl: "https://example.com/images/cloud-gaps.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "Networking ROI: One Event = 3 Months of LinkedIn Alone",
            content: "Quantified: Virtual meetups yield 5x connections. Scripts for Nigerian tech conferences like DataFest.",
            link: "https://ppalink.com/blog/networking-roi",
            ctaText: "Attend Next Event",
            imageUrl: "https://example.com/images/networking.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "Remote vs. Hybrid: 55% of Roles Now Offer Flexibility",
            content: "Post-pandemic shift: Productivity data shows hybrid wins. Pros/cons for career growth.",
            link: "https://ppalink.com/insights/remote-hybrid",
            ctaText: "Update Preferences",
            imageUrl: "https://example.com/images/hybrid-work.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.CAREER_INSIGHT,
            audience: FeedAudience.CANDIDATE,
            title: "From Intern to Full-Time: Conversion Rates by Industry",
            content: "FinTech: 70% convert. Tips to stand out during internships, including side projects.",
            link: "https://ppalink.com/blog/intern-conversion",
            ctaText: "Land Internship",
            imageUrl: "https://example.com/images/internships.jpg",
            userId: candidateUserId,
        },
    ];

    // --- SUCCESS_STORY (20 items) ---
    const successStoryItems = [
        // Original 10
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "Adeola's Journey: From NYSC Corper to Paystack Software Engineer",
            content: " 'PPALink's skill quizzes proved my React skills without a degree—got me shortlisted in days.' Adeola (Batch C 2022) shares her prep routine, interview tips, and first-day jitters. Now earning ₦450k + equity.",
            link: "https://ppalink.com/stories/adeola-paystack",
            ctaText: "Read Full Story",
            imageUrl: "https://example.com/images/adeola-success.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "PPA to Permanent: John's Retention Story at a Lagos FinTech Firm",
            content: "After NYSC at a startup PPA, John used PPALink to showcase projects and network. 'The platform connected me to the hiring manager directly.' Transitioned to full-time backend role with 50% raise.",
            link: "https://ppalink.com/stories/john-retention",
            ctaText: "Get Inspired",
            imageUrl: "https://example.com/images/john-nysc.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "Career Switch: From Law Graduate to Tech Product Manager at Opay",
            content: "Funmi self-taught via PPALink resources, passed PM quiz (92%). 'No CS background? No problem—focus on user empathy.' Her 6-month pivot includes bootcamp recs and LinkedIn outreach script.",
            link: "https://ppalink.com/stories/funmi-switch",
            ctaText: "Start Your Switch",
            imageUrl: "https://example.com/images/career-switch.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "Inside Andela: Recruiter Interview on What Makes a Standout Candidate",
            content: "Tunde, Andela's Talent Lead, reveals: 'We hire for potential—verified quizzes show grit.' Stories from 5 hires, plus application dos/don'ts for their bootcamp.",
            link: "https://ppalink.com/stories/andela-interview",
            ctaText: "Apply to Andela",
            imageUrl: "https://example.com/images/andela-recruiter.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "Startup Founder's Tale: Hiring Our First Dev Through PPALink",
            content: "Chinedu, CEO of a HealthTech startup: 'Filtered 200 apps to 5 verified profiles in hours.' Saved 3 weeks on recruitment. Includes their job post template for agencies.",
            link: "https://ppalink.com/stories/startup-hire",
            ctaText: "For Founders",
            imageUrl: "https://example.com/images/startup-success.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "5 PPALink Users Who Landed Jobs in Under 30 Days: Their Strategies",
            content: "From daily applications to targeted quizzes: Fatima (UI/UX at ₦300k), etc. Common thread: Verified profiles + follow-up emails. Download their timelines.",
            link: "https://ppalink.com/stories/fast-hires",
            ctaText: "Steal Their Playbook",
            imageUrl: "https://example.com/images/fast-job-stories.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "Verified Power: Chiamaka's Profile Views Up 300% Post-NYSC Check",
            content: "'Before: Crickets. After: 15 shortlists.' Step-by-step verification guide + her updated summary that sealed deals. Now at a remote EdTech role.",
            link: "https://ppalink.com/stories/chiamaka-verified",
            ctaText: "Verify Your NYSC",
            imageUrl: "https://example.com/images/verification-story.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "Relo Success: From Kano to Lagos Tech Hub in 3 Months",
            content: "Ibrahim's move: Used PPALink's location filters, prepped relocation questions. 'Negotiated moving stipend.' Tips for northern candidates eyeing southern opportunities.",
            link: "https://ppalink.com/stories/relo-story",
            ctaText: "Plan Your Move",
            imageUrl: "https://example.com/images/relocation-success.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "Acing 3 PPALink Quizzes: Top Scorer's Study Hacks",
            content: "Adaora (95% avg): 'Flashcards + practice projects.' Her routine for JS, SQL, PM quizzes. Result: Offer from Interswitch. Free study planner inside.",
            link: "https://ppalink.com/stories/quiz-hacks",
            ctaText: "Ace Your Next Quiz",
            imageUrl: "https://example.com/images/quiz-success.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "Agency Love: Why a Pro-Tier Firm Hires Exclusively via PPALink",
            content: "HR at a 200-person agency: 'Verified data cuts ghosting by 70%.' Their workflow: Shortlist > Quiz > Interview. For recruiters: Upgrade tips.",
            link: "https://ppalink.com/stories/agency-spotlight",
            ctaText: "For Recruiters",
            imageUrl: "https://example.com/images/agency-story.jpg",
            userId: candidateUserId,
        },
        // Additional 10
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "From Corper to Consultant: Ngozi's Big Four Breakthrough",
            content: "'PPALink's case study resources prepped me for Deloitte interviews.' Her 4-month journey, including networking events that led to the offer.",
            link: "https://ppalink.com/stories/ngozi-consultant",
            ctaText: "Prep Cases",
            imageUrl: "https://example.com/images/big-four-story.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "Bootcamp Grad's First Gig: ₦250k Remote Frontend Role",
            content: "Emeka completed AltSchool, aced PPALink quizzes. 'Portfolio + verification = quick hire.' Timeline and resource list shared.",
            link: "https://ppalink.com/stories/emeka-bootcamp",
            ctaText: "Enroll in Bootcamp",
            imageUrl: "https://example.com/images/bootcamp-success.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "Overcoming Rejection: 50 Apps to Dream Job at PiggyVest",
            content: "Lessons from failures: Tailored CVs, skill gaps filled via quizzes. 'Persistence pays—now at ₦380k.'",
            link: "https://ppalink.com/stories/rejection-to-hire",
            ctaText: "Keep Applying",
            imageUrl: "https://example.com/images/rejection-story.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "NYSC Tech Corps: Building Apps During Service Year",
            content: "Sade developed 3 apps during PPA, showcased on PPALink. Landed dev role pre-pop. 'Service year as launchpad.'",
            link: "https://ppalink.com/stories/nysc-tech",
            ctaText: "Build During NYSC",
            imageUrl: "https://example.com/images/nysc-apps.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "Diversity Hire Spotlight: LGBTQ+ in Nigerian Corporate Tech",
            content: "Anonymous story: Navigating safe spaces, ally networks. 'PPALink's anonymous quizzes leveled the field.'",
            link: "https://ppalink.com/stories/diversity-hire",
            ctaText: "Share Your Story",
            imageUrl: "https://example.com/images/diversity-success.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "Side Hustle to Full-Time: E-commerce Dev at a Startup",
            content: "Tobi's WooCommerce site led to a role. 'PPALink connected my hustle to employers.' Scaling tips included.",
            link: "https://ppalink.com/stories/side-hustle",
            ctaText: "Monetize Skills",
            imageUrl: "https://example.com/images/side-hustle.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "Post-Maternity Return: Balancing Family and Frontend Career",
            content: "Aisha's comeback: Updated skills via PPALink, flexible roles. 'Verification rebuilt confidence fast.'",
            link: "https://ppalink.com/stories/maternity-return",
            ctaText: "Return Strong",
            imageUrl: "https://example.com/images/return-to-work.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "Rural Talent Rising: Internet Café to Cloud Engineer",
            content: "From Ogun village: Self-taught AWS, verified on PPALink. Remote job at ₦300k. Access tips for low-bandwidth learners.",
            link: "https://ppalink.com/stories/rural-talent",
            ctaText: "Learn Anywhere",
            imageUrl: "https://example.com/images/rural-success.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "Quiz Master to Manager: Promotion Path at a Bank",
            content: "Bankole aced 5 quizzes, fast-tracked to team lead. 'Data-backed skills opened doors.' Leadership lessons.",
            link: "https://ppalink.com/stories/quiz-to-manager",
            ctaText: "Lead with Skills",
            imageUrl: "https://example.com/images/promotion-story.jpg",
            userId: candidateUserId,
        },
        {
            type: FeedType.SUCCESS_STORY,
            category: FeedCategory.SUCCESS_STORY,
            audience: FeedAudience.CANDIDATE,
            title: "Collaborative Win: Team Project Lands Group Hires",
            content: "Hackathon team from PPALink: All 4 hired at a FinTech. 'Networking + shared portfolio = multiplier effect.'",
            link: "https://ppalink.com/stories/team-hire",
            ctaText: "Team Up",
            imageUrl: "https://example.com/images/team-success.jpg",
            userId: candidateUserId,
        },
    ];

    // --- FROM_EMPLOYERS (20 items) ---
    const fromEmployersItems = [
        // Original 6 + 4 to make 10
        {
            type: FeedType.EVENT,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "First Bank Graduate Trainee Program: Virtual Info Session",
            content: "Aspiring bankers, join us on Oct 25 for insights into our 12-month program. Covers rotations in retail, digital banking, and risk. Speakers: C-suite execs. Apply during the session—spots limited to 100.",
            link: "https://ppalink.com/events/firstbank-info",
            ctaText: "Secure Your Spot",
            imageUrl: "https://example.com/images/firstbank-event.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "A Day in the Life of a Flutterwave Backend Engineer",
            content: "From 8 AM standups to debugging payments APIs—Ola shares his routine at Africa's unicorn. Perks: Unlimited PTO, stock options. See if this fast-paced env fits you.",
            link: "https://ppalink.com/blog/flutterwave-day",
            ctaText: "Explore Flutterwave",
            imageUrl: "https://example.com/images/flutterwave-engineer.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "Dangote Group's Take: Essential Traits for Project Managers",
            content: "Our PM Lead: 'Adaptability > Tools knowledge.' From our 500+ hires: PMP cert helps, but real-world agility wins. See our interview framework.",
            link: "https://ppalink.com/insights/dangote-pm",
            ctaText: "View Open Roles",
            imageUrl: "https://example.com/images/dangote-insight.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.EVENT,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "KPMG Nigeria Graduate Recruitment: Open Day at Our Lagos Office",
            content: "Oct 18: Tour facilities, mock case interviews, networking with partners. For final-years/grads in accounting, consulting. Dress code: Business casual. 200 spots.",
            link: "https://ppalink.com/events/kpmg-openday",
            ctaText: "RSVP Now",
            imageUrl: "https://example.com/images/kpmg-event.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "MTN's Commitment to Diversity: Building Inclusive Teams in Telecom",
            content: "40% women in tech roles goal by 2026. Stories from our ERGs, plus how we support neurodiversity. If values align, check our inclusion quiz for fit.",
            link: "https://ppalink.com/blog/mtn-diversity",
            ctaText: "Join MTN",
            imageUrl: "https://example.com/images/mtn-culture.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "Demystifying Our 4-Stage Interview at a Leading Agency",
            content: "Stage 1: CV screen. 2: Skill quiz. 3: Behavioral. 4: Offer chat. 60% pass rate. Pro tips from our TA team to prep each round.",
            link: "https://ppalink.com/insights/interview-process",
            ctaText: "Prep for Interviews",
            imageUrl: "https://example.com/images/interview-stages.jpg",
            userId: agencyUserId,
        },
        // Additional 4 to complete original 10
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "Life at GTBank: Innovation in Digital Banking",
            content: "From API integrations to customer apps—meet the team driving mobile money. Career paths in product and compliance. Equity and wellness perks highlighted.",
            link: "https://ppalink.com/blog/gtbank-life",
            ctaText: "Careers at GTBank",
            imageUrl: "https://example.com/images/gtbank-day.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.EVENT,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "Shell Nigeria Tech Talk: Energy Sector Digital Transformation",
            content: "Nov 5: Engineers discuss IoT in oilfields and data analytics for sustainability. Q&A with hiring managers. For STEM grads.",
            link: "https://ppalink.com/events/shell-tech",
            ctaText: "Attend Talk",
            imageUrl: "https://example.com/images/shell-event.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "Unilever's View: Sustainability Skills in FMCG Hiring",
            content: "ESG focus: 50% of roles now require green certs. Our talent pipeline and internship conversions (80%).",
            link: "https://ppalink.com/insights/unilever-sustain",
            ctaText: "Green Skills",
            imageUrl: "https://example.com/images/unilever-insight.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "P&G Nigeria: From Graduate to Global Leader",
            content: "12-month trainee program alumni stories. Focus on marketing and supply chain. Global rotations available.",
            link: "https://ppalink.com/blog/pg-careers",
            ctaText: "Apply to P&G",
            imageUrl: "https://example.com/images/pg-story.jpg",
            userId: agencyUserId,
        },
        // Additional 10 more
        {
            type: FeedType.EVENT,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "Deloitte Digital Day: Consulting for the Future",
            content: "Oct 30: Workshops on blockchain and AI ethics. Network with partners; apply to analyst roles on-site.",
            link: "https://ppalink.com/events/deloitte-digital",
            ctaText: "Register",
            imageUrl: "https://example.com/images/deloitte-event.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "Nestlé Nigeria: Nutrition Tech and Career Growth",
            content: "R&D roles in food innovation. From lab to market: A scientist's path. Learning budgets and mentorship.",
            link: "https://ppalink.com/blog/nestle-tech",
            ctaText: "Innovate with Us",
            imageUrl: "https://example.com/images/nestle-day.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "PwC's Hiring Pulse: Audit and Advisory Trends",
            content: "Rise in forensic accounting post-fraud cases. Skills: Data viz, Python for audits. 70% internal promotions.",
            link: "https://ppalink.com/insights/pwc-trends",
            ctaText: "Audit Careers",
            imageUrl: "https://example.com/images/pwc-insight.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.EVENT,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "Chevron Nigeria Forum: Engineering Excellence",
            content: "Nov 10: Panel on upstream tech and safety. For petroleum engineers; resume reviews included.",
            link: "https://ppalink.com/events/chevron-forum",
            ctaText: "Join Forum",
            imageUrl: "https://example.com/images/chevron-event.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "Lagos State Civil Service: Digital Gov Initiatives",
            content: "E-gov projects hiring devs and analysts. Public sector perks: Stability, pensions. Entry paths for grads.",
            link: "https://ppalink.com/blog/lagos-civil",
            ctaText: "Serve Public",
            imageUrl: "https://example.com/images/civil-service.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "Indomie Factory Insights: Supply Chain Careers",
            content: "Logistics roles booming with exports. Certs: APICS. From warehouse to exec: Promotion tracks.",
            link: "https://ppalink.com/insights/indomie-chain",
            ctaText: "Chain Careers",
            imageUrl: "https://example.com/images/supply-chain.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.EVENT,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "UBA Innovation Challenge: FinTech Pitch Day",
            content: "Submit ideas for banking apps. Winners get funding + roles. For creative grads in design/coding.",
            link: "https://ppalink.com/events/uba-challenge",
            ctaText: "Pitch Idea",
            imageUrl: "https://example.com/images/uba-event.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "DHL Nigeria: Logistics in the E-Commerce Era",
            content: "Drone deliveries and AI routing. Careers in ops and data. Global exposure for locals.",
            link: "https://ppalink.com/blog/dhl-logistics",
            ctaText: "Deliver Impact",
            imageUrl: "https://example.com/images/dhl-day.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.INSIGHT,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "Zenith Bank's Tech Stack: Careers in Core Banking Systems",
            content: "Finacle and Temenos expertise needed. Training programs for juniors. Security focus hires up 25%.",
            link: "https://ppalink.com/insights/zenith-tech",
            ctaText: "Bank Tech Roles",
            imageUrl: "https://example.com/images/zenith-insight.jpg",
            userId: agencyUserId,
        },
        {
            type: FeedType.ARTICLE,
            category: FeedCategory.FROM_EMPLOYERS,
            audience: FeedAudience.CANDIDATE,
            title: "Coca-Cola Nigeria: Marketing in a Competitive Market",
            content: "Brand campaigns and digital ads. From intern to brand manager: Success paths shared.",
            link: "https://ppalink.com/blog/coca-marketing",
            ctaText: "Brand Careers",
            imageUrl: "https://example.com/images/coca-story.jpg",
            userId: agencyUserId,
        },
    ];

    // Create all items with varying timestamps
    const allPromises = [
        ...learnGrowItems.map(createItem),
        ...careerInsightItems.map(createItem),
        ...successStoryItems.map(createItem),
        ...fromEmployersItems.map(createItem),
    ];

    await Promise.all(allPromises);

    console.log(`✅ ${allPromises.length} static feed items seeded with varying timestamps and authorship.`);
}