export const industries = [
    // Finance & Professional Services
    { name: 'Finance & Professional Services', isHeading: true, order: 1 },
    { name: 'Accounting', order: 2 },
    { name: 'Auditing', order: 3 },
    { name: 'Banking', order: 4 },
    { name: 'Financial Services', order: 5 },
    { name: 'Insurance', order: 6 },
    { name: 'Legal', order: 7 },
    { name: 'Venture Capital', order: 8 },
    { name: 'Investment', order: 9 },
  
    // Business & Management
    { name: 'Business & Management', isHeading: true, order: 10 },
    { name: 'Consulting', order: 11 },
    { name: 'Business Strategy', order: 12 },
    { name: 'Management', order: 13 },
    { name: 'Human Resources', order: 14 },
    { name: 'Recruitment', order: 15 },
    { name: 'Marketing', order: 16 },
    { name: 'Public Relations', order: 17 },
    { name: 'Advertising', order: 18 },
    { name: 'Media', order: 19 },
    { name: 'Communications', order: 20 },
    { name: 'Research', order: 21 },
    { name: 'Development', order: 22 },
  
    // Technology & Digital
    { name: 'Technology & Digital', isHeading: true, order: 23 },
    { name: 'ICT', order: 24 },
    { name: 'Software', order: 25 },
    { name: 'Technology', order: 26 },
    { name: 'Telecommunications', order: 27 },
    { name: 'Cybersecurity', order: 28 },
    { name: 'Data', order: 29 },
    { name: 'Analytics', order: 30 },
    { name: 'E-Commerce', order: 31 },
    { name: 'Gaming', order: 32 },
    { name: 'Entertainment Tech', order: 33 },
    { name: 'FinTech', order: 34 },
  
    // Education
    { name: 'Education', isHeading: true, order: 35 },
    { name: 'Teaching', order: 36 },
    { name: 'Training', order: 37 },
    { name: 'E-Learning', order: 38 },
    { name: 'EdTech', order: 39 },
    { name: 'Capacity Building', order: 40 },
  
    // Healthcare
    { name: 'Healthcare', isHeading: true, order: 41 },
    { name: 'Medical Services', order: 42 },
    { name: 'Hospitals', order: 43 },
    { name: 'Clinics', order: 44 },
    { name: 'Pharmaceutical', order: 45 },
    { name: 'Biotechnology', order: 46 },
    { name: 'Public Health', order: 47 },
    { name: 'Fitness', order: 48 },
    { name: 'Wellness', order: 49 },
  
    // Agriculture & Food
    { name: 'Agriculture & Food', isHeading: true, order: 50 },
    { name: 'Agriculture', order: 51 },
    { name: 'Agro-Allied', order: 52 },
    { name: 'Fisheries', order: 53 },
    { name: 'Aquaculture', order: 54 },
    { name: 'Forestry', order: 55 },
    { name: 'Food Processing', order: 56 },
    { name: 'Retail', order: 57 },
    { name: 'FMCG', order: 58 },
  
    // Energy & Natural Resources
    { name: 'Energy & Natural Resources', isHeading: true, order: 59 },
    { name: 'Oil & Gas', order: 60 },
    { name: 'Energy', order: 61 },
    { name: 'Power', order: 62 },
    { name: 'Utilities', order: 63 },
    { name: 'Renewable Energy', order: 64 },
    { name: 'Mining', order: 65 },
    { name: 'Extraction', order: 66 },
  
    // Engineering & Manufacturing
    { name: 'Engineering & Manufacturing', isHeading: true, order: 67 },
    { name: 'Engineering', order: 68 },
    { name: 'Technical Services', order: 69 },
    { name: 'Construction', order: 70 },
    { name: 'Real Estate', order: 71 },
    { name: 'Architecture', order: 72 },
    { name: 'Design', order: 73 },
    { name: 'Manufacturing', order: 74 },
    { name: 'Production', order: 75 },
    { name: 'Industrial Automation', order: 76 },
  
    // Transport & Logistics
    { name: 'Transport & Logistics', isHeading: true, order: 77 },
    { name: 'Logistics', order: 78 },
    { name: 'Supply Chain', order: 79 },
    { name: 'Aviation', order: 80 },
    { name: 'Aerospace', order: 81 },
    { name: 'Maritime', order: 82 },
    { name: 'Shipping', order: 83 },
    { name: 'Rail Transport', order: 84 },
    { name: 'Road Transport', order: 85 },
    { name: 'Ride-hailing', order: 86 },
    { name: 'Delivery Services', order: 87 },
  
    // Government & Public Sector
    { name: 'Government & Public Sector', isHeading: true, order: 88 },
    { name: 'Government', order: 89 },
    { name: 'Public Service', order: 90 },
    { name: 'NGO', order: 91 },
    { name: 'Non-Profit', order: 92 },
    { name: 'International Organizations', order: 93 },
    { name: 'Security Services', order: 94 },
    { name: 'Military', order: 95 },
    { name: 'Defense', order: 96 },
  
    // Creative & Lifestyle
    { name: 'Creative & Lifestyle', isHeading: true, order: 97 },
    { name: 'Arts', order: 98 },
    { name: 'Culture', order: 99 },
    { name: 'Hospitality', order: 100 },
    { name: 'Tourism', order: 101 },
    { name: 'Events Management', order: 102 },
    { name: 'Fashion', order: 103 },
    { name: 'Beauty', order: 104 },
    { name: 'Sports', order: 105 },
    { name: 'Recreation', order: 106 },
    { name: 'Entertainment', order: 107 },
    { name: 'Music', order: 108 },
    { name: 'Film', order: 109 },
  ];
  