interface QuestionData {
  text: string;
  options: [string, string, string, string];
  correctAnswer: string;
}

export const quizData: Record<string, QuestionData[]> = {
  // --- Technical & Engineering ---
  'software-development': [
    { text: 'What is the primary goal of the "Agile" methodology?', options: ['Detailed upfront planning', 'Strict adherence to the initial plan', 'Iterative development and customer feedback', 'Minimizing documentation'], correctAnswer: 'Iterative development and customer feedback' },
    { text: 'What does the acronym "API" stand for?', options: ['Application Programming Interface', 'Automated Programming Instruction', 'Application Process Integration', 'Advanced Programming Interface'], correctAnswer: 'Application Programming Interface' },
    { text: 'In version control, what is the purpose of a "branch"?', options: ['To merge code into the main line', 'To store a backup of the code', 'To create an isolated environment for new development', 'To deploy the code to production'], correctAnswer: 'To create an isolated environment for new development' },
    { text: 'What does "refactoring" mean in software development?', options: ['Adding new features', 'Fixing bugs', 'Rewriting code from scratch', 'Restructuring existing code without changing its external behavior'], correctAnswer: 'Restructuring existing code without changing its external behavior' },
  ],
  'frontend-development': [
    { text: 'What are the three core technologies of the web?', options: ['HTML, CSS, JavaScript', 'React, Angular, Vue', 'HTTP, FTP, SMTP', 'JSON, XML, YAML'], correctAnswer: 'HTML, CSS, JavaScript' },
    { text: 'What is the purpose of a CSS "media query"?', options: ['To play media files', 'To query a database', 'To apply styles based on device characteristics like screen size', 'To animate elements'], correctAnswer: 'To apply styles based on device characteristics like screen size' },
    { text: 'What is "state" in the context of a frontend framework like React?', options: ['The visual appearance of a component', 'Data that a component manages and can change over time', 'A static set of properties', 'A connection to the backend'], correctAnswer: 'Data that a component manages and can change over time' },
    { text: 'What does "bundling" mean in frontend development?', options: ['Combining multiple JavaScript/CSS files into a single file', 'Compressing images', 'Deploying the website', 'Testing the code'], correctAnswer: 'Combining multiple JavaScript/CSS files into a single file' },
  ],
  'backend-development': [
    { text: 'Which of the following is a primary responsibility of a backend system?', options: ['Rendering the user interface', 'Managing the database and application logic', 'Styling web pages', 'Handling user clicks'], correctAnswer: 'Managing the database and application logic' },
    { text: 'What is a "RESTful API"?', options: ['An API that is very fast', 'An API that uses a specific programming language', 'An architectural style for designing networked applications', 'An API for real-time communication'], correctAnswer: 'An architectural style for designing networked applications' },
    { text: 'In a database, what is a "primary key"?', options: ['The first column in a table', 'A unique identifier for each record in a table', 'A key used for encryption', 'A foreign user ID'], correctAnswer: 'A unique identifier for each record in a table' },
    { text: 'What is the purpose of "caching" in a backend system?', options: ['To log errors', 'To store temporary data for faster access', 'To secure the database', 'To validate user input'], correctAnswer: 'To store temporary data for faster access' },
  ],
  'mobile-app-development': [
    { text: 'Which language is primarily used for native Android development?', options: ['Swift', 'JavaScript', 'Kotlin', 'C#'], correctAnswer: 'Kotlin' },
    { text: 'Which language is primarily used for native iOS development?', options: ['Java', 'Swift', 'Python', 'Go'], correctAnswer: 'Swift' },
    { text: 'What is a popular cross-platform framework for mobile development?', options: ['React Native', 'Django', 'Spring Boot', 'Laravel'], correctAnswer: 'React Native' },
    { text: 'What is the purpose of an "SDK" in mobile development?', options: ['A code editor', 'A design tool', 'A Software Development Kit with tools and libraries', 'A testing framework'], correctAnswer: 'A Software Development Kit with tools and libraries' },
  ],
  'javascript': [
    { text: 'Which keyword is used to declare a variable that cannot be reassigned?', options: ['let', 'var', 'const', 'static'], correctAnswer: 'const' },
    { text: 'What does the "===" operator check for?', options: ['Value equality only', 'Reference equality', 'Value and type equality', 'Type equality only'], correctAnswer: 'Value and type equality' },
    { text: 'Which built-in method adds one or more elements to the end of an array?', options: ['shift()', 'unshift()', 'push()', 'pop()'], correctAnswer: 'push()' },
    { text: 'What is a "Promise" in JavaScript?', options: ['A guarantee of code execution', 'An object representing the eventual completion or failure of an asynchronous operation', 'A type of variable', 'A syntax for loops'], correctAnswer: 'An object representing the eventual completion or failure of an asynchronous operation' },
  ],
  'typescript': [
    { text: 'What is the main advantage of TypeScript over JavaScript?', options: ['It runs faster', 'It adds static typing to JavaScript', 'It has more built-in functions', 'It requires less code'], correctAnswer: 'It adds static typing to JavaScript' },
    { text: 'How do you define an interface in TypeScript?', options: ['class MyInterface {}', 'type MyInterface = {};', 'struct MyInterface {}', 'interface MyInterface {}'], correctAnswer: 'interface MyInterface {}' },
    { text: 'What file extension is commonly used for TypeScript files?', options: ['.js', '.ts', '.tsx', '.tt'], correctAnswer: '.ts' },
    { text: 'What is the "any" type in TypeScript?', options: ['A type for numbers only', 'A type that can be any value, opting out of type checking', 'A type for strings only', 'An error type'], correctAnswer: 'A type that can be any value, opting out of type checking' },
  ],
  'react': [
    { text: 'In React, what is used to pass data to a component from outside?', options: ['state', 'props', 'render', 'setState'], correctAnswer: 'props' },
    { text: 'Which hook should be used for performing side effects in a function component?', options: ['useState', 'useContext', 'useEffect', 'useReducer'], correctAnswer: 'useEffect' },
    { text: 'What is the virtual DOM?', options: ['A direct copy of the real DOM', 'A representation of the DOM kept in memory for reconciliation', 'A tool for debugging', 'A browser feature'], correctAnswer: 'A representation of the DOM kept in memory for reconciliation' },
    { text: 'What must be unique among a list of sibling elements in React?', options: ['The `id` prop', 'The `className` prop', 'The `key` prop', 'The `name` prop'], correctAnswer: 'The `key` prop' },
  ],
  'nodejs': [
    { text: 'What is Node.js primarily used for?', options: ['Client-side scripting', 'Server-side scripting', 'Mobile app development', 'Styling web pages'], correctAnswer: 'Server-side scripting' },
    { text: 'What is the name of the Node.js package manager?', options: ['npx', 'node', 'npm', 'yarn'], correctAnswer: 'npm' },
    { text: 'Which core module is used to create a web server in Node.js?', options: ['fs', 'http', 'url', 'path'], correctAnswer: 'http' },
    { text: 'What is the "event loop" in Node.js?', options: ['A type of `for` loop', 'A mechanism that allows Node.js to perform non-blocking I/O operations', 'A security feature', 'A way to handle errors'], correctAnswer: 'A mechanism that allows Node.js to perform non-blocking I/O operations' },
  ],
  'python': [
    { text: 'Which of the following data types is mutable in Python?', options: ['int', 'str', 'tuple', 'list'], correctAnswer: 'list' },
    { text: 'What keyword is used to define a function in Python?', options: ['func', 'def', 'function', 'define'], correctAnswer: 'def' },
    { text: 'How do you create a single-line comment in Python?', options: ['// comment', '/* comment */', '# comment', '<!-- comment -->'], correctAnswer: '# comment' },
    { text: 'What does the `len()` function do?', options: ['Calculates the length of a file', 'Returns the number of items in an object like a list or string', 'Converts a variable to a number', 'Finds the largest number in a list'], correctAnswer: 'Returns the number of items in an object like a list or string' },
  ],
  'django': [
    { text: 'What is Django?', options: ['A JavaScript framework', 'A Python web framework', 'A database', 'A templating language'], correctAnswer: 'A Python web framework' },
    { text: 'What does "ORM" stand for in the context of Django?', options: ['Object-Relational Mapping', 'Object-Request Model', 'Online-Resource Manager', 'Object-Response Middleware'], correctAnswer: 'Object-Relational Mapping' },
    { text: 'Which file in a Django app is used to define URL patterns?', options: ['models.py', 'views.py', 'settings.py', 'urls.py'], correctAnswer: 'urls.py' },
    { text: 'What command is used to apply database migrations in Django?', options: ['runserver', 'startapp', 'makemigrations', 'migrate'], correctAnswer: 'migrate' },
  ],
  'java': [
    { text: 'What is the main entry point for a Java application?', options: ['The `start()` method', 'The `main()` method', 'The `run()` method', 'The constructor'], correctAnswer: 'The `main()` method' },
    { text: 'Which of these is NOT a primitive data type in Java?', options: ['int', 'float', 'boolean', 'String'], correctAnswer: 'String' },
    { text: 'What does "JVM" stand for?', options: ['Java Virtual Machine', 'Java Visual Machine', 'Java Version Manager', 'Java Verified Module'], correctAnswer: 'Java Virtual Machine' },
    { text: 'What keyword is used to create an object in Java?', options: ['create', 'new', 'instance', 'object'], correctAnswer: 'new' },
  ],
  'spring-boot': [
    { text: 'What is the primary goal of Spring Boot?', options: ['To create mobile applications', 'To simplify the development of production-ready Spring applications', 'To manage databases', 'To design user interfaces'], correctAnswer: 'To simplify the development of production-ready Spring applications' },
    { text: 'What is "dependency injection" in Spring?', options: ['A way to manage database connections', 'A design pattern where objects receive their dependencies from an external source', 'A method for handling errors', 'A security feature'], correctAnswer: 'A design pattern where objects receive their dependencies from an external source' },
    { text: 'Which annotation is used to mark a class as a REST controller?', options: ['@Controller', '@Component', '@Service', '@RestController'], correctAnswer: '@RestController' },
    { text: 'What is the default embedded server in a Spring Boot web application?', options: ['Jetty', 'GlassFish', 'Tomcat', 'WildFly'], correctAnswer: 'Tomcat' },
  ],
  'ui-ux-design': [
    { text: 'What is a "wireframe" in UI/UX design?', options: ['A high-fidelity visual design', 'A low-fidelity, basic layout of a webpage', 'The final version of the product', 'A user testing script'], correctAnswer: 'A low-fidelity, basic layout of a webpage' },
    { text: 'What is the primary goal of "user research"?', options: ['To design the logo', 'To understand user behaviors, needs, and motivations', 'To write the code', 'To market the product'], correctAnswer: 'To understand user behaviors, needs, and motivations' },
    { text: 'What does "usability" refer to?', options: ['How visually appealing a product is', 'How easy a product is to use', 'How fast the product loads', 'How secure the product is'], correctAnswer: 'How easy a product is to use' },
    { text: 'What is a "persona" in UX design?', options: ['A real user', 'A fictional character representing a target user group', 'A type of wireframe', 'A project stakeholder'], correctAnswer: 'A fictional character representing a target user group' },
  ],
  'data-analysis': [
    { text: 'What is the "mean" of a dataset?', options: ['The middle value', 'The most frequent value', 'The average of all values', 'The range of values'], correctAnswer: 'The average of all values' },
    { text: 'Which of these is a common tool for data visualization?', options: ['Microsoft Word', 'Tableau', 'Adobe Photoshop', 'Notepad'], correctAnswer: 'Tableau' },
    { text: 'What is "data cleaning"?', options: ['Deleting old data', 'Archiving data', 'The process of detecting and correcting corrupt or inaccurate records', 'Visualizing data'], correctAnswer: 'The process of detecting and correcting corrupt or inaccurate records' },
    { text: 'What does SQL stand for?', options: ['Structured Query Language', 'Simple Query Logic', 'Standard Question Language', 'System Query Link'], correctAnswer: 'Structured Query Language' },
  ],
  'data-science': [
    { text: 'What is the difference between supervised and unsupervised learning?', options: ['Supervised uses labeled data, unsupervised uses unlabeled data', 'Supervised is for classification, unsupervised is for regression', 'Supervised is faster', 'There is no difference'], correctAnswer: 'Supervised uses labeled data, unsupervised uses unlabeled data' },
    { text: 'What is "overfitting" in machine learning?', options: ['The model is too simple', 'The model performs well on new, unseen data', 'The model performs well on training data but poorly on new data', 'The model fails to train'], correctAnswer: 'The model performs well on training data but poorly on new data' },
    { text: 'Which Python library is fundamental for scientific computing and arrays?', options: ['Pandas', 'Matplotlib', 'Scikit-learn', 'NumPy'], correctAnswer: 'NumPy' },
    { text: 'What is "feature engineering"?', options: ['Designing the UI for a model', 'Using domain knowledge to create new input variables for a model', 'Deploying a model to production', 'Testing a model for accuracy'], correctAnswer: 'Using domain knowledge to create new input variables for a model' },
  ],
  'machine-learning': [
    { text: 'Which of these is a common classification algorithm?', options: ['K-Means Clustering', 'Linear Regression', 'Support Vector Machine (SVM)', 'Principal Component Analysis (PCA)'], correctAnswer: 'Support Vector Machine (SVM)' },
    { text: 'What is a "neural network"?', options: ['A biological brain model', 'A computer network topology', 'A computing system inspired by the structure of the human brain', 'A type of database'], correctAnswer: 'A computing system inspired by the structure of the human brain' },
    { text: 'What is a "training set" used for?', options: ['To evaluate the final model', 'To fit the parameters of a model', 'To validate the model during development', 'To store the final model'], correctAnswer: 'To fit the parameters of a model' },
    { text: 'What does "hyperparameter tuning" involve?', options: ['Adjusting the weights of a neural network', 'Cleaning the input data', 'Finding the optimal configuration settings for a model', 'Visualizing the model results'], correctAnswer: 'Finding the optimal configuration settings for a model' },
  ],
  'cybersecurity': [
    { text: 'What is "phishing"?', options: ['A type of firewall', 'An attempt to steal sensitive information by disguising as a trustworthy entity', 'A method of encrypting data', 'A physical security measure'], correctAnswer: 'An attempt to steal sensitive information by disguising as a trustworthy entity' },
    { text: 'What is the purpose of a "firewall"?', options: ['To speed up the network', 'To monitor and control incoming and outgoing network traffic', 'To encrypt files', 'To back up data'], correctAnswer: 'To monitor and control incoming and outgoing network traffic' },
    { text: 'What does "MFA" stand for?', options: ['Multi-Factor Authentication', 'Multiple-Firewall Architecture', 'Managed File Access', 'Malware-Free Application'], correctAnswer: 'Multi-Factor Authentication' },
    { text: 'What is "encryption"?', options: ['Deleting data securely', 'The process of converting information into a code to prevent unauthorized access', 'Scanning for viruses', 'Creating a backup'], correctAnswer: 'The process of converting information into a code to prevent unauthorized access' },
  ],
  'network-engineering': [
    { text: 'What is an "IP address"?', options: ['A physical hardware address', 'A numerical label assigned to each device connected to a computer network', 'A type of network cable', 'A brand of router'], correctAnswer: 'A numerical label assigned to each device connected to a computer network' },
    { text: 'What does "LAN" stand for?', options: ['Large Area Network', 'Logical Area Network', 'Local Area Network', 'Long Area Network'], correctAnswer: 'Local Area Network' },
    { text: 'What is the function of a "router"?', options: ['To connect devices within the same LAN', 'To forward data packets between different computer networks', 'To provide power to network devices', 'To block viruses'], correctAnswer: 'To forward data packets between different computer networks' },
    { text: 'What does "DNS" stand for?', options: ['Domain Name System', 'Dynamic Network Service', 'Data Naming Standard', 'Digital Network Security'], correctAnswer: 'Domain Name System' },
  ],
  'cloud-computing-aws-azure-gcp': [
    { text: 'What is the primary benefit of cloud computing?', options: ['It is always cheaper', 'It provides on-demand access to computing resources over the internet', 'It is more secure than on-premise servers', 'It requires no technical knowledge'], correctAnswer: 'It provides on-demand access to computing resources over the internet' },
    { text: 'Which AWS service is used for scalable object storage?', options: ['EC2', 'RDS', 'S3', 'Lambda'], correctAnswer: 'S3' },
    { text: 'Which Azure service is equivalent to AWS EC2 for virtual machines?', options: ['Azure Functions', 'Azure SQL Database', 'Azure Blob Storage', 'Azure Virtual Machines'], correctAnswer: 'Azure Virtual Machines' },
    { text: 'What does "IaaS" stand for?', options: ['Internet as a Service', 'Infrastructure as a Service', 'Integration as a Service', 'Information as a Service'], correctAnswer: 'Infrastructure as a Service' },
  ],
  'aws': [
    { text: 'Which AWS service provides resizable compute capacity in the cloud (virtual servers)?', options: ['S3', 'EC2', 'RDS', 'DynamoDB'], correctAnswer: 'EC2' },
    { text: 'What is AWS Lambda?', options: ['A virtual machine service', 'A serverless compute service that runs your code in response to events', 'A database service', 'A storage service'], correctAnswer: 'A serverless compute service that runs your code in response to events' },
    { text: 'Which AWS service is a managed relational database service?', options: ['S3', 'DynamoDB', 'EC2', 'RDS'], correctAnswer: 'RDS' },
    { text: 'What is an "IAM" user in AWS?', options: ['A customer of your application', 'An Identity and Access Management entity with specific permissions', 'A type of EC2 instance', 'A billing contact'], correctAnswer: 'An Identity and Access Management entity with specific permissions' },
  ],
  'google-cloud': [
    { text: 'What is the Google Cloud equivalent of AWS EC2?', options: ['Cloud Storage', 'Cloud Functions', 'Compute Engine', 'BigQuery'], correctAnswer: 'Compute Engine' },
    { text: 'Which Google Cloud service is a serverless, scalable data warehouse?', options: ['Cloud SQL', 'Cloud Spanner', 'Bigtable', 'BigQuery'], correctAnswer: 'BigQuery' },
    { text: 'What is Google Kubernetes Engine (GKE)?', options: ['A virtual machine service', 'A managed environment for deploying containerized applications', 'A storage service', 'A machine learning platform'], correctAnswer: 'A managed environment for deploying containerized applications' },
    { text: 'Which service is used for object storage in Google Cloud?', options: ['Cloud Storage', 'Persistent Disk', 'Cloud SQL', 'Filestore'], correctAnswer: 'Cloud Storage' },
  ],
  'microsoft-azure': [
    { text: 'What is the Azure equivalent of AWS S3?', options: ['Azure Virtual Machines', 'Azure SQL Database', 'Azure Blob Storage', 'Azure Functions'], correctAnswer: 'Azure Blob Storage' },
    { text: 'Which Azure service is a serverless compute service?', options: ['Azure App Service', 'Azure Kubernetes Service (AKS)', 'Azure Functions', 'Azure Virtual Machines'], correctAnswer: 'Azure Functions' },
    { text: 'What is Azure Active Directory (AAD)?', options: ['A virtual network service', 'A content delivery network', 'A cloud-based identity and access management service', 'A database service'], correctAnswer: 'A cloud-based identity and access management service' },
    { text: 'Which Azure service is a managed relational database service?', options: ['Cosmos DB', 'Azure SQL Database', 'Blob Storage', 'Table Storage'], correctAnswer: 'Azure SQL Database' },
  ],
  'devops': [
    { text: 'What is the core philosophy of DevOps?', options: ['To separate development and operations teams', 'To automate everything', 'To improve collaboration between development and operations teams', 'To write code faster'], correctAnswer: 'To improve collaboration between development and operations teams' },
    { text: 'What does "CI/CD" stand for?', options: ['Continuous Integration / Continuous Delivery', 'Code Integration / Code Deployment', 'Continuous Implementation / Continuous Development', 'Code Implementation / Code Delivery'], correctAnswer: 'Continuous Integration / Continuous Delivery' },
    { text: 'What is "Infrastructure as Code" (IaC)?', options: ['Writing code for infrastructure hardware', 'Managing and provisioning infrastructure through code and automation', 'A type of network diagram', 'A physical server'], correctAnswer: 'Managing and provisioning infrastructure through code and automation' },
    { text: 'Which of the following is a popular CI/CD tool?', options: ['Jenkins', 'Photoshop', 'Microsoft Word', 'Figma'], correctAnswer: 'Jenkins' },
  ],
  'docker': [
    { text: 'What is a "Docker container"?', options: ['A virtual machine', 'A lightweight, standalone, executable package that includes everything needed to run a piece of software', 'A type of server', 'A code repository'], correctAnswer: 'A lightweight, standalone,executable package that includes everything needed to run a piece of software' },
    { text: 'What is a "Docker image"?', options: ['A running instance of a container', 'A template for creating a Docker container', 'A backup of a container', 'A network for containers'], correctAnswer: 'A template for creating a Docker container' },
    { text: 'What is the name of the file used to build a Docker image?', options: ['build.sh', 'docker.yml', 'Dockerfile', 'run.py'], correctAnswer: 'Dockerfile' },
    { text: 'What is the purpose of Docker Hub?', options: ['To run containers', 'A registry for storing and sharing Docker images', 'A tool for monitoring containers', 'A code editor'], correctAnswer: 'A registry for storing and sharing Docker images' },
  ],
  'kubernetes': [
    { text: 'What is the primary function of Kubernetes?', options: ['To build container images', 'To run a single container', 'To automate the deployment, scaling, and management of containerized applications', 'To write application code'], correctAnswer: 'To automate the deployment, scaling, and management of containerized applications' },
    { text: 'What is a "Pod" in Kubernetes?', options: ['The smallest deployable unit, representing a single instance of a running process', 'A group of servers', 'A network policy', 'A storage volume'], correctAnswer: 'The smallest deployable unit, representing a single instance of a running process' },
    { text: 'What is a "Service" in Kubernetes?', options: ['A worker node', 'The master node', 'An abstract way to expose an application running on a set of Pods as a network service', 'A configuration file'], correctAnswer: 'An abstract way to expose an application running on a set of Pods as a network service' },
    { text: 'What is `kubectl`?', options: ['The Kubernetes master process', 'A container runtime', 'The command-line tool for interacting with a Kubernetes cluster', 'A monitoring dashboard'], correctAnswer: 'The command-line tool for interacting with a Kubernetes cluster' },
  ],
  'terraform': [
    { text: 'What is Terraform used for?', options: ['Writing application logic', 'Building container images', 'Provisioning and managing infrastructure as code', 'Running tests'], correctAnswer: 'Provisioning and managing infrastructure as code' },
    { text: 'What language are Terraform configurations written in?', options: ['YAML', 'JSON', 'HashiCorp Configuration Language (HCL)', 'Python'], correctAnswer: 'HashiCorp Configuration Language (HCL)' },
    { text: 'What does the `terraform apply` command do?', options: ['Shows what changes will be made', 'Initializes the backend', 'Creates or updates infrastructure according to the configuration files', 'Destroys the infrastructure'], correctAnswer: 'Creates or updates infrastructure according to the configuration files' },
    { text: 'What is the "state file" in Terraform?', options: ['A log file', 'A record of the infrastructure that Terraform manages', 'A variable definition file', 'A provider plugin'], correctAnswer: 'A record of the infrastructure that Terraform manages' },
  ],
  'ci-cd': [
    { text: 'What is the primary goal of Continuous Integration (CI)?', options: ['To deploy to production automatically', 'To frequently merge code changes into a central repository and run automated builds and tests', 'To manually test the code', 'To write documentation'], correctAnswer: 'To frequently merge code changes into a central repository and run automated builds and tests' },
    { text: 'What is Continuous Delivery (CD)?', options: ['The same as Continuous Integration', 'The practice of automatically deploying code changes to a production-like environment after the build stage', 'Manually deploying code', 'Running only unit tests'], correctAnswer: 'The practice of automatically deploying code changes to a production-like environment after the build stage' },
    { text: 'What is a "build artifact"?', options: ['A bug found in the code', 'The compiled and packaged code ready for deployment', 'A test script', 'A server configuration file'], correctAnswer: 'The compiled and packaged code ready for deployment' },
    { text: 'Which of these is a key benefit of CI/CD?', options: ['Fewer deployments', 'Larger code changes per release', 'Faster and more reliable release cycles', 'Longer testing phases'], correctAnswer: 'Faster and more reliable release cycles' },
  ],
  'git': [
    { text: 'What is `git commit` used for?', options: ['To upload changes to a remote repository', 'To record changes to the local repository', 'To discard changes', 'To create a new branch'], correctAnswer: 'To record changes to the local repository' },
    { text: 'What does `git pull` do?', options: ['Uploads your local changes', 'Fetches changes from a remote repository and merges them into the current branch', 'Shows the status of your working directory', 'Switches to a different branch'], correctAnswer: 'Fetches changes from a remote repository and merges them into the current branch' },
    { text: 'What is a "merge conflict"?', options: ['A type of bug', 'When Git cannot automatically resolve differences in code between two commits', 'A security vulnerability', 'An error in the remote repository'], correctAnswer: 'When Git cannot automatically resolve differences in code between two commits' },
    { text: 'What is the purpose of a `.gitignore` file?', options: ['To store your Git credentials', 'To specify intentionally untracked files that Git should ignore', 'To list all files in the repository', 'To define the project version'], correctAnswer: 'To specify intentionally untracked files that Git should ignore' },
  ],
  'database-management-sql-nosql': [
    { text: 'What is a key difference between SQL and NoSQL databases?', options: ['SQL is for web, NoSQL is for mobile', 'SQL databases are typically relational, while NoSQL databases are non-relational', 'SQL is older and no longer used', 'SQL is less secure than NoSQL'], correctAnswer: 'SQL databases are typically relational, while NoSQL databases are non-relational' },
    { text: 'Which of the following is a popular NoSQL database?', options: ['PostgreSQL', 'MySQL', 'MongoDB', 'SQL Server'], correctAnswer: 'MongoDB' },
    { text: 'What does "ACID" stand for in the context of database transactions?', options: ['Atomicity, Consistency, Isolation, Durability', 'Association, Connection, Integrity, Data', 'Action, Commit, Isolation, Durability', 'Atomicity, Concurrency, Integrity, Data'], correctAnswer: 'Atomicity, Consistency, Isolation, Durability' },
    { text: 'What is a database "index"?', options: ['The first record in a table', 'A data structure that improves the speed of data retrieval operations', 'A backup of the database', 'A security policy'], correctAnswer: 'A data structure that improves the speed of data retrieval operations' },
  ],
  'quality-assurance': [
    { text: 'What is the primary goal of Quality Assurance (QA)?', options: ['To write all the code', 'To prevent defects and ensure the quality of the final product', 'To design the user interface', 'To deploy the application'], correctAnswer: 'To prevent defects and ensure the quality of the final product' },
    { text: 'What is "regression testing"?', options: ['Testing new features', 'Re-running functional and non-functional tests to ensure that previously developed software still performs after a change', 'Testing the performance of an application', 'Testing by the end-users'], correctAnswer: 'Re-running functional and non-functional tests to ensure that previously developed software still performs after a change' },
    { text: 'What is a "bug report"?', options: ['A summary of the project', 'A document outlining the features to be built', 'A detailed report of a defect found in the software', 'A performance metric'], correctAnswer: 'A detailed report of a defect found in the software' },
    { text: 'What is the difference between black-box and white-box testing?', options: ['Black-box tests internal structure, white-box tests functionality', 'Black-box tests functionality without looking at the internal code, white-box tests the internal structures', 'They are the same', 'Black-box is automated, white-box is manual'], correctAnswer: 'Black-box tests functionality without looking at the internal code, white-box tests the internal structures' },
  ],
  'technical-writing': [
    { text: 'What is the primary audience for technical documentation?', options: ['Marketing team', 'End-users, developers, or administrators who need to understand how to use a product', 'The CEO', 'Investors'], correctAnswer: 'End-users, developers, or administrators who need to understand how to use a product' },
    { text: 'What is a "style guide" in technical writing?', options: ['A list of features', 'A set of standards for the writing and design of documents', 'A marketing plan', 'A project timeline'], correctAnswer: 'A set of standards for the writing and design of documents' },
    { text: 'What is "single-sourcing" in documentation?', options: ['Using only one author', 'Writing content once and reusing it in multiple formats or documents', 'Writing for only one audience', 'Using only one font'], correctAnswer: 'Writing content once and reusing it in multiple formats or documents' },
    { text: 'Which of these is a key principle of good technical writing?', options: ['Using complex jargon', 'Clarity and conciseness', 'Writing long, detailed paragraphs', 'Focusing on the author\'s perspective'], correctAnswer: 'Clarity and conciseness' },
  ],
  'hardware-engineering': [
    { text: 'What is a "PCB" in hardware engineering?', options: ['Personal Computer Board', 'Printed Circuit Board', 'Power Control Block', 'Processor Communication Bus'], correctAnswer: 'Printed Circuit Board' },
    { text: 'What is "CAD" software used for in hardware design?', options: ['Writing code', 'Computer-Aided Design for creating 2D and 3D models', 'Testing software', 'Managing project timelines'], correctAnswer: 'Computer-Aided Design for creating 2D and 3D models' },
    { text: 'What does a "microcontroller" typically include?', options: ['Only a CPU', 'A CPU, memory, and programmable input/output peripherals on a single chip', 'A power supply', 'A display screen'], correctAnswer: 'A CPU, memory, and programmable input/output peripherals on a single chip' },
    { text: 'What is "soldering"?', options: ['A process of joining electrical components using a filler metal', 'A type of computer chip', 'A software debugging technique', 'A way to cool down components'], correctAnswer: 'A process of joining electrical components using a filler metal' },
  ],
  'financial-analysis': [
    { text: 'Which financial statement summarizes revenues and expenses over a period?', options: ['Balance Sheet', 'Income Statement', 'Cash Flow Statement', 'Statement of Equity'], correctAnswer: 'Income Statement' },
    { text: 'What does "EBITDA" stand for?', options: ['Earnings Before Interest, Taxes, Depreciation, and Amortization', 'Earnings Before Income, Taxes, and Debt Adjustments', 'Estimated Business Income, Tax, and Depreciation', 'Equity Before Interest, Taxes, and Debt'], correctAnswer: 'Earnings Before Interest, Taxes, Depreciation, and Amortization' },
    { text: 'What is a "Discounted Cash Flow" (DCF) analysis used for?', options: ['To calculate a company\'s current profit', 'To estimate the value of an investment based on its expected future cash flows', 'To determine a company\'s debt level', 'To analyze a company\'s stock price history'], correctAnswer: 'To estimate the value of an investment based on its expected future cash flows' },
    { text: 'What does the "P/E ratio" measure?', options: ['A company\'s profitability', 'A company\'s debt', 'A company\'s stock price relative to its per-share earnings', 'A company\'s asset value'], correctAnswer: 'A company\'s stock price relative to its per-share earnings' },
  ],
  'auditing': [
    { text: 'What is the primary role of an external auditor?', options: ['To manage the company\'s finances', 'To provide an independent opinion on the fairness of a company\'s financial statements', 'To prepare the company\'s tax returns', 'To set the company\'s budget'], correctAnswer: 'To provide an independent opinion on the fairness of a company\'s financial statements' },
    { text: 'What is "materiality" in auditing?', options: ['The quality of the audit evidence', 'The importance or significance of an amount, transaction, or discrepancy', 'The auditor\'s level of experience', 'The fee paid for the audit'], correctAnswer: 'The importance or significance of an amount, transaction, or discrepancy' },
    { text: 'What are "internal controls"?', options: ['Security guards at the company office', 'Processes and procedures implemented to ensure the integrity of financial and accounting information', 'The company\'s marketing strategy', 'The IT department\'s hardware'], correctAnswer: 'Processes and procedures implemented to ensure the integrity of financial and accounting information' },
    { text: 'What is an "unqualified opinion" in an audit report?', options: ['A negative report', 'A report indicating the auditor has reservations', 'A clean report indicating the financial statements are presented fairly', 'A report where the auditor could not gather enough evidence'], correctAnswer: 'A clean report indicating the financial statements are presented fairly' },
  ],
  'investment-management': [
    { text: 'What is "asset allocation"?', options: ['Choosing a single stock to invest in', 'The strategy of dividing an investment portfolio among different asset categories', 'Selling all investments', 'A type of mutual fund'], correctAnswer: 'The strategy of dividing an investment portfolio among different asset categories' },
    { text: 'What is a "mutual fund"?', options: ['A fund that invests in only one company', 'A professionally managed investment fund that pools money from many investors to purchase securities', 'A government bond', 'A type of bank account'], correctAnswer: 'A professionally managed investment fund that pools money from many investors to purchase securities' },
    { text: 'What is "diversification"?', options: ['Investing in only one industry', 'A risk management strategy of mixing a wide variety of investments within a portfolio', 'Focusing on high-risk stocks', 'Investing in a single currency'], correctAnswer: 'A risk management strategy of mixing a wide variety of investments within a portfolio' },
    { text: 'What is a "bull market"?', options: ['A market where prices are falling', 'A market where prices are expected to rise', 'A market with low trading volume', 'A highly regulated market'], correctAnswer: 'A market where prices are expected to rise' },
  ],
  'risk-management': [
    { text: 'What is the first step in the risk management process?', options: ['Treating the risk', 'Monitoring the risk', 'Identifying the risk', 'Evaluating the risk'], correctAnswer: 'Identifying the risk' },
    { text: 'What is "risk appetite"?', options: ['The amount of risk a company has taken', 'The level of risk an organization is prepared to accept', 'A specific risk event', 'A risk mitigation plan'], correctAnswer: 'The level of risk an organization is prepared to accept' },
    { text: 'What is "risk mitigation"?', options: ['Accepting a risk', 'The process of reducing the impact or likelihood of a risk', 'Ignoring a risk', 'Transferring a risk to another party'], correctAnswer: 'The process of reducing the impact or likelihood of a risk' },
    { text: 'What is a "heat map" used for in risk management?', options: ['To track temperature changes', 'A graphical representation of risk data where values are depicted by color', 'A financial statement', 'A project timeline'], correctAnswer: 'A graphical representation of risk data where values are depicted by color' },
  ],
  'business-analysis': [
    { text: 'What is a primary role of a Business Analyst?', options: ['To write the code', 'To act as a bridge between business stakeholders and the technical team', 'To manage the project budget', 'To design the company logo'], correctAnswer: 'To act as a bridge between business stakeholders and the technical team' },
    { text: 'What does "SWOT" analysis stand for?', options: ['Strategy, Weaknesses, Opportunities, Threats', 'Strengths, Weaknesses, Opportunities, Threats', 'Software, Web, Operations, Technology', 'Sales, Work, Operations, Team'], correctAnswer: 'Strengths, Weaknesses, Opportunities, Threats' },
    { text: 'What is a "user story" in Agile development?', options: ['A detailed technical specification', 'A high-level, informal description of a software feature from an end-user perspective', 'A bug report', 'A project plan'], correctAnswer: 'A high-level, informal description of a software feature from an end-user perspective' },
    { text: 'What is the purpose of "requirements elicitation"?', options: ['To test the software', 'To deploy the software', 'The practice of collecting requirements from stakeholders', 'To design the database'], correctAnswer: 'The practice of collecting requirements from stakeholders' },
  ],
  'human-resources': [
    { text: 'What is "onboarding" in HR?', options: ['The process of hiring a new employee', 'The process of integrating a new employee into an organization', 'Conducting a job interview', 'Advertising a job opening'], correctAnswer: 'The process of integrating a new employee into an organization' },
    { text: 'Which of the following is a key function of an HR department?', options: ['Product marketing', 'Recruitment and staffing', 'Managing the company\'s finances', 'Developing software'], correctAnswer: 'Recruitment and staffing' },
    { text: 'What is "performance management"?', options: ['A disciplinary process', 'An ongoing process of communication between a supervisor and an employee', 'The annual company party', 'The payroll system'], correctAnswer: 'An ongoing process of communication between a supervisor and an employee' },
    { text: 'What is an "Employee Value Proposition" (EVP)?', options: ['An employee\'s salary', 'The set of benefits an employer offers to employees in return for their skills and experience', 'The company\'s stock price', 'A legal contract'], correctAnswer: 'The set of benefits an employer offers to employees in return for their skills and experience' },
  ],
  'recruitment': [
    { text: 'What is "sourcing" in recruitment?', options: ['Conducting the final interview', 'The proactive search for qualified candidates for current or future open roles', 'Making a job offer', 'Onboarding a new hire'], correctAnswer: 'The proactive search for qualified candidates for current or future open roles' },
    { text: 'What is an "Applicant Tracking System" (ATS)?', options: ['A payroll system', 'A software application that enables the electronic handling of recruitment needs', 'A performance review tool', 'A social media platform'], correctAnswer: 'A software application that enables the electronic handling of recruitment needs' },
    { text: 'What is a "behavioral interview" question?', options: ['A question about technical skills', 'A question that asks a candidate to describe past behavior to predict future performance', 'A brain-teaser question', 'A question about the candidate\'s hobbies'], correctAnswer: 'A question that asks a candidate to describe past behavior to predict future performance' },
    { text: 'What does "time-to-hire" measure?', options: ['The length of the interview', 'The time it takes to onboard a new employee', 'The number of days between a job opening being posted and a candidate accepting an offer', 'The notice period of a candidate'], correctAnswer: 'The number of days between a job opening being posted and a candidate accepting an offer' },
  ],
  'business-development': [
    { text: 'What is the primary goal of business development?', options: ['Managing existing customer accounts', 'Creating long-term value for an organization from customers, markets, and relationships', 'Developing the company\'s website', 'Internal team training'], correctAnswer: 'Creating long-term value for an organization from customers, markets, and relationships' },
    { text: 'What is a "lead" in a business development context?', options: ['A current customer', 'A potential customer or sales prospect', 'A competitor', 'A project manager'], correctAnswer: 'A potential customer or sales prospect' },
    { text: 'What is a "strategic partnership"?', options: ['A relationship between two companies to achieve a common goal', 'A merger between two companies', 'A customer-supplier relationship', 'Hiring a new employee'], correctAnswer: 'A relationship between two companies to achieve a common goal' },
    { text: 'What does "market penetration" mean?', options: ['Entering a new geographic market', 'A strategy to increase the market share of an existing product', 'Developing a new product', 'Acquiring another company'], correctAnswer: 'A strategy to increase the market share of an existing product' },
  ],
  'supply-chain-management': [
    { text: 'What are the core components of supply chain management?', options: ['Marketing, Sales, and HR', 'Planning, Sourcing, Manufacturing, Delivery, and Returns', 'Finance, Accounting, and Auditing', 'Software Development and IT Support'], correctAnswer: 'Planning, Sourcing, Manufacturing, Delivery, and Returns' },
    { text: 'What does "inventory" refer to?', options: ['The company\'s buildings', 'The raw materials, work-in-process goods, and completely finished goods that are considered to be the portion of a business\'s assets', 'The company\'s employees', 'The company\'s financial capital'], correctAnswer: 'The raw materials, work-in-process goods, and completely finished goods that are considered to be the portion of a business\'s assets' },
    { text: 'What is "logistics"?', options: ['The process of creating a product', 'The detailed coordination of a complex operation involving many people, facilities, or supplies', 'The marketing of a product', 'The financial planning for a product'], correctAnswer: 'The detailed coordination of a complex operation involving many people, facilities, or supplies' },
    { text: 'What does "Just-In-Time" (JIT) inventory system aim to do?', options: ['Keep large stockpiles of inventory', 'Reduce inventory levels and associated costs by receiving goods only as they are needed in the production process', 'Order inventory once a year', 'Use multiple suppliers for every component'], correctAnswer: 'Reduce inventory levels and associated costs by receiving goods only as they are needed in the production process' },
  ],
  'operations-management': [
    { text: 'What is the primary focus of operations management?', options: ['Marketing and sales strategies', 'Managing the process of creating goods and services', 'Hiring and training employees', 'Financial reporting'], correctAnswer: 'Managing the process of creating goods and services' },
    { text: 'What is "Lean Manufacturing"?', options: ['A production method aimed at reducing waste and maximizing productivity', 'A method for building large, complex products', 'A marketing technique', 'A financial accounting standard'], correctAnswer: 'A production method aimed at reducing waste and maximizing productivity' },
    { text: 'What is "quality control"?', options: ['A process of ensuring products or services meet a certain standard of quality', 'The marketing of a product', 'The pricing of a product', 'The a process of ensuring products or services meet a certain standard of quality'], correctAnswer: 'A process of ensuring products or services meet a certain standard of quality' },
    { text: 'What does "bottleneck" mean in operations?', options: ['A stage in a process that causes the entire process to slow down or stop', 'The final stage of production', 'A high-performing part of the process', 'A safety procedure'], correctAnswer: 'A stage in a process that causes the entire process to slow down or stop' },
  ],
  'content-marketing': [
    { text: 'What is the primary goal of content marketing?', options: ['To directly sell a product', 'To attract and retain a clearly defined audience by creating and distributing valuable, relevant content', 'To design the company website', 'To manage social media accounts'], correctAnswer: 'To attract and retain a clearly defined audience by creating and distributing valuable, relevant content' },
    { text: 'What is an "editorial calendar"?', options: ['A list of company holidays', 'A schedule used by publishers and marketers to control the publication of content across different media', 'A budget for marketing', 'A list of employees'], correctAnswer: 'A schedule used by publishers and marketers to control the publication of content across different media' },
    { text: 'What is a "call-to-action" (CTA)?', options: ['A phone number', 'An instruction to the audience to provoke an immediate response, such as "call now" or "find out more"', 'A headline', 'A blog post comment'], correctAnswer: 'An instruction to the audience to provoke an immediate response, such as "call now" or "find out more"' },
    { text: 'What is "evergreen content"?', options: ['Content about environmental topics', 'Content that is only relevant for a short time', 'Content that remains relevant and valuable for a long period of time', 'Content that is updated daily'], correctAnswer: 'Content that remains relevant and valuable for a long period of time' },
  ],
  'social-media-management': [
    { text: 'Which of the following is a key metric for social media engagement?', options: ['Number of followers', 'Likes, comments, and shares', 'Website clicks', 'Ad spend'], correctAnswer: 'Likes, comments, and shares' },
    { text: 'What is a "content calendar" for social media?', options: ['A list of followers', 'A schedule of when and what content will be posted on social media platforms', 'A budget for social media ads', 'A report of past performance'], correctAnswer: 'A schedule of when and what content will be posted on social media platforms' },
    { text: 'What is the purpose of using hashtags?', options: ['To hide a post', 'To make content discoverable to users interested in a specific topic', 'To tag a person', 'To format text'], correctAnswer: 'To make content discoverable to users interested in a specific topic' },
    { text: 'What is "A/B testing" in social media?', options: ['Testing two different social media platforms', 'Comparing two versions of a post or ad to see which performs better', 'Analyzing a competitor\'s account', 'Scheduling posts for different times'], correctAnswer: 'Comparing two versions of a post or ad to see which performs better' },
  ],
  'email-marketing': [
    { text: 'What is the "open rate" in email marketing?', options: ['The percentage of emails that were delivered', 'The percentage of recipients who opened the email', 'The percentage of people who clicked a link', 'The percentage of people who unsubscribed'], correctAnswer: 'The percentage of recipients who opened the email' },
    { text: 'What is a "drip campaign"?', options: ['A single email sent to all subscribers', 'A set of automated emails sent out on a schedule', 'An email that contains a video', 'A marketing email sent by mistake'], correctAnswer: 'A set of automated emails sent out on a schedule' },
    { text: 'What is the purpose of a "call-to-action" (CTA) button in an email?', options: ['To unsubscribe', 'To encourage the reader to take a specific action, like visiting a website', 'To display an image', 'To mark the email as spam'], correctAnswer: 'To encourage the reader to take a specific action, like visiting a website' },
    { text: 'What does "segmentation" mean in email marketing?', options: ['Sending the same email to everyone', 'Dividing your email list into smaller groups based on specific criteria', 'Deleting inactive subscribers', 'Designing the email template'], correctAnswer: 'Dividing your email list into smaller groups based on specific criteria' },
  ],
  'brand-management': [
    { text: 'What is "brand identity"?', options: ['The company\'s logo', 'The collection of all elements that a company creates to portray the right image to its consumer', 'The company\'s mission statement', 'A product\'s price'], correctAnswer: 'The collection of all elements that a company creates to portray the right image to its consumer' },
    { text: 'What is "brand equity"?', options: ['The financial value of a brand', 'The number of products a brand sells', 'A brand\'s logo', 'The commercial value that derives from consumer perception of the brand name of a particular product or service'], correctAnswer: 'The commercial value that derives from consumer perception of the brand name of a particular product or service' },
    { text: 'What is a "brand guideline"?', options: ['A marketing budget', 'A document that specifies how a brand should be represented to the public', 'A list of competitors', 'A sales script'], correctAnswer: 'A document that specifies how a brand should be represented to the public' },
    { text: 'What is "rebranding"?', options: ['Creating a new product', 'Changing a company\'s corporate image', 'Running a new ad campaign', 'Hiring a new CEO'], correctAnswer: 'Changing a company\'s corporate image' },
  ],
  'public-relations': [
    { text: 'What is the primary goal of public relations (PR)?', options: ['To directly sell products', 'To manage the spread of information between an individual or an organization and the public', 'To create advertisements', 'To manage social media accounts'], correctAnswer: 'To manage the spread of information between an individual or an organization and the public' },
    { text: 'What is a "press release"?', options: ['An internal company memo', 'An official statement delivered to members of the news media', 'A social media post', 'A customer review'], correctAnswer: 'An official statement delivered to members of the news media' },
    { text: 'What is "crisis management" in PR?', options: ['The process of planning a company event', 'The process by which an organization deals with a disruptive and unexpected event that threatens to harm the organization or its stakeholders', 'Daily social media posting', 'Creating a new logo'], correctAnswer: 'The process by which an organization deals with a disruptive and unexpected event that threatens to harm the organization or its stakeholders' },
    { text: 'What is a "media kit"?', options: ['A package of information for journalists and media outlets', 'A set of TV commercials', 'A list of company employees', 'A financial report'], correctAnswer: 'A package of information for journalists and media outlets' },
  ],
  'corporate-communications': [
    { text: 'Who is the primary audience for "internal communications"?', options: ['Customers', 'Investors', 'The general public', 'Employees'], correctAnswer: 'Employees' },
    { text: 'What is a key objective of corporate communications?', options: ['To increase sales directly', 'To build and maintain a company\'s reputation and brand', 'To manage the IT department', 'To develop new products'], correctAnswer: 'To build and maintain a company\'s reputation and brand' },
    { text: 'What does "stakeholder engagement" involve?', options: ['Only communicating with shareholders', 'Communicating and interacting with all groups that have an interest in the organization', 'Running ad campaigns', 'Designing a website'], correctAnswer: 'Communicating and interacting with all groups that have an interest in the organization' },
    { text: 'What is a "corporate social responsibility" (CSR) report?', options: ['A financial statement', 'A document that communicates a company\'s CSR activities and impact', 'A marketing brochure', 'An employee handbook'], correctAnswer: 'A document that communicates a company\'s CSR activities and impact' },
  ],
  'video-production': [
    { text: 'What are the three main stages of video production?', options: ['Writing, Directing, Acting', 'Pre-production, Production, and Post-production', 'Shooting, Editing, and Uploading', 'Concept, Budgeting, and Marketing'], correctAnswer: 'Pre-production, Production, and Post-production' },
    { text: 'What is a "storyboard"?', options: ['The final video script', 'A graphic organizer in the form of illustrations or images displayed in sequence', 'The camera used for shooting', 'The editing software'], correctAnswer: 'A graphic organizer in the form of illustrations or images displayed in sequence' },
    { text: 'What does "B-roll" refer to?', options: ['The main footage of the primary subject', 'Supplemental or alternative footage intercut with the main shot', 'Blooper or outtake footage', 'The audio track'], correctAnswer: 'Supplemental or alternative footage intercut with the main shot' },
    { text: 'What is "color grading"?', options: ['Adjusting the volume of the audio', 'The process of altering and enhancing the color of a motion picture, video image, or still image', 'Adding special effects', 'Writing the script'], correctAnswer: 'The process of altering and enhancing the color of a motion picture, video image, or still image' },
  ],
  'creative-writing': [
    { text: 'What is "show, don\'t tell"?', options: ['A rule about using only dialogue', 'A writing technique that allows the reader to experience the story through actions, words, and feelings, rather than through summarization', 'A grammar rule', 'A way to format a script'], correctAnswer: 'A writing technique that allows the reader to experience the story through actions, words, and feelings, rather than through summarization' },
    { text: 'What is a "plot twist"?', options: ['The beginning of a story', 'A radical change in the expected direction or outcome of the plot', 'The main character', 'The setting of the story'], correctAnswer: 'A radical change in the expected direction or outcome of the plot' },
    { text: 'What is "foreshadowing"?', options: ['A literary device in which a writer gives an advance hint of what is to come later in the story', 'Describing the weather', 'Developing a character\'s backstory', 'The ending of the story'], correctAnswer: 'A literary device in which a writer gives an advance hint of what is to come later in the story' },
    { text: 'What is a "protagonist"?', options: ['The main villain', 'The main character of a story', 'A minor character', 'The narrator'], correctAnswer: 'The main character of a story' },
  ],
  'market-research': [
    { text: 'What is the difference between primary and secondary research?', options: ['Primary is new research you conduct yourself, secondary is existing data', 'Primary is qualitative, secondary is quantitative', 'Primary is expensive, secondary is free', 'Primary is online, secondary is offline'], correctAnswer: 'Primary is new research you conduct yourself, secondary is existing data' },
    { text: 'What is a "focus group"?', options: ['A survey sent to a large number of people', 'A form of qualitative research in which a group of people are asked about their perceptions and opinions', 'A one-on-one interview', 'An analysis of sales data'], correctAnswer: 'A form of qualitative research in which a group of people are asked about their perceptions and opinions' },
    { text: 'What is "quantitative research"?', options: ['Research that deals with non-numerical data', 'Research that deals with numbers and statistics', 'Research based on observation', 'Research conducted on the internet'], correctAnswer: 'Research that deals with numbers and statistics' },
    { text: 'What is a "target audience"?', options: ['All potential customers', 'A specific group of consumers most likely to be interested in your product or service', 'Your company\'s employees', 'Your competitors\' customers'], correctAnswer: 'A specific group of consumers most likely to be interested in your product or service' },
  ],
  'customer-service': [
    { text: 'What is a key trait of a good customer service representative?', options: ['Speaking quickly', 'Empathy and patience', 'Ignoring complaints', 'Upselling at all costs'], correctAnswer: 'Empathy and patience' },
    { text: 'What does "CRM" stand for in customer service?', options: ['Customer Complaint Resolution', 'Customer Relationship Management', 'Client Response Management', 'Company Rules Manual'], correctAnswer: 'Customer Relationship Management' },
    { text: 'What is "First Contact Resolution" (FCR)?', options: ['Responding to a customer within 24 hours', 'Resolving a customer\'s issue during the first interaction', 'The first step in handling a complaint', 'A follow-up email'], correctAnswer: 'Resolving a customer\'s issue during the first interaction' },
    { text: 'What is a good way to handle an angry customer?', options: ['Argue with them', 'Hang up', 'Listen actively, empathize, and offer a solution', 'Transfer them to another department immediately'], correctAnswer: 'Listen actively, empathize, and offer a solution' },
  ],
  'data-entry': [
    { text: 'What is a key skill for accurate data entry?', options: ['Fast typing speed', 'Attention to detail', 'Ability to multitask', 'Strong negotiation skills'], correctAnswer: 'Attention to detail' },
    { text: 'What is "data validation"?', options: ['The process of ensuring that data is clean, correct, and useful', 'Deleting old data', 'Entering data quickly', 'Creating a backup of the data'], correctAnswer: 'The process of ensuring that data is clean, correct, and useful' },
    { text: 'What does "WPM" stand for in the context of typing?', options: ['Words Per Minute', 'Work Performance Metric', 'Web Page Management', 'Written Paragraphs Monthly'], correctAnswer: 'Words Per Minute' },
    { text: 'What is a "spreadsheet"?', options: ['A word processing document', 'A computer application for organization, analysis, and storage of data in tabular form', 'A database', 'An email client'], correctAnswer: 'A computer application for organization, analysis, and storage of data in tabular form' },
  ],
  'administrative-support': [
    { text: 'Which of the following is a common task for an administrative assistant?', options: ['Developing software', 'Scheduling appointments and managing calendars', 'Designing marketing campaigns', 'Conducting financial audits'], correctAnswer: 'Scheduling appointments and managing calendars' },
    { text: 'What is "minute taking" in a meeting?', options: ['Timing the meeting', 'The process of recording the key discussions and decisions made during a meeting', 'Presenting a topic', 'Setting the meeting agenda'], correctAnswer: 'The process of recording the key discussions and decisions made during a meeting' },
    { text: 'Which software is commonly used for creating presentations?', options: ['Microsoft Excel', 'Microsoft PowerPoint', 'Adobe Photoshop', 'Microsoft Word'], correctAnswer: 'Microsoft PowerPoint' },
    { text: 'What is a key quality of a good administrative professional?', options: ['Creativity', 'Strong organizational skills', 'Physical strength', 'Public speaking ability'], correctAnswer: 'Strong organizational skills' },
  ],
  'legal-compliance': [
    { text: 'What is the primary role of a compliance officer?', options: ['To market the company', 'To ensure that an organization is complying with its outside regulatory and legal requirements, as well as internal policies', 'To manage the company\'s finances', 'To develop new products'], correctAnswer: 'To ensure that an organization is complying with its outside regulatory and legal requirements, as well as internal policies' },
    { text: 'What does "AML" stand for in finance?', options: ['Anti-Money Laundering', 'Asset Management Logic', 'Annual Market Loan', 'Automated Machine Learning'], correctAnswer: 'Anti-Money Laundering' },
    { text: 'What is a "whistleblower" policy?', options: ['A policy about company parties', 'A policy that protects employees who report misconduct or illegal activities within an organization', 'A social media policy', 'A dress code policy'], correctAnswer: 'A policy that protects employees who report misconduct or illegal activities within an organization' },
    { text: 'What is "due diligence" in a business context?', options: ['The process of investigating a business or person prior to signing a contract', 'A marketing campaign', 'A financial audit', 'A product launch'], correctAnswer: 'The process of investigating a business or person prior to signing a contract' },
  ],
  'contract-negotiation': [
    { text: 'What is a "BATNA" in negotiation?', options: ['Best Alternative To a Negotiated Agreement', 'Basic Agreement Terms and Nuances', 'Bargaining and Tactical Negotiation Approach', 'Buyer\'s Alternative to the Agreement'], correctAnswer: 'Best Alternative To a Negotiated Agreement' },
    { text: 'What is a "win-win" negotiation outcome?', options: ['One party wins, the other loses', 'Both parties lose', 'An outcome where both parties feel they have gained and the agreement is mutually beneficial', 'The negotiation ends in a stalemate'], correctAnswer: 'An outcome where both parties feel they have gained and the agreement is mutually beneficial' },
    { text: 'What is an "indemnity" clause in a contract?', options: ['A clause that sets the payment terms', 'A clause that transfers risk from one party to another, making one party responsible for losses', 'A clause that defines the contract duration', 'A confidentiality clause'], correctAnswer: 'A clause that transfers risk from one party to another, making one party responsible for losses' },
    { text: 'What is "arbitration" in contract disputes?', options: ['Going to court', 'A form of alternative dispute resolution where a neutral third party makes a binding decision', 'Ignoring the dispute', 'Renegotiating the contract'], correctAnswer: 'A form of alternative dispute resolution where a neutral third party makes a binding decision' },
  ],
  'leadership': [
    { text: 'What is a key difference between leadership and management?', options: ['They are the same', 'Leadership is about inspiring and motivating, while management is about planning and organizing', 'Leadership is only for senior executives', 'Management does not involve people'], correctAnswer: 'Leadership is about inspiring and motivating, while management is about planning and organizing' },
    { text: 'What is "transformational leadership"?', options: ['A style where leaders focus on transactions and rewards', 'A style where leaders inspire and motivate followers to achieve extraordinary outcomes', 'A hands-off leadership style', 'An authoritarian leadership style'], correctAnswer: 'A style where leaders inspire and motivate followers to achieve extraordinary outcomes' },
    { text: 'What is "emotional intelligence" (EQ)?', options: ['A person\'s IQ', 'The ability to understand, use, and manage your own emotions in positive ways', 'A measure of academic knowledge', 'A type of personality test'], correctAnswer: 'The ability to understand, use, and manage your own emotions in positive ways' },
    { text: 'What is a common characteristic of an effective leader?', options: ['Micromanaging the team', 'Strong communication skills', 'Avoiding difficult decisions', 'Taking all the credit'], correctAnswer: 'Strong communication skills' },
  ],
  'team-management': [
    { text: 'What is "delegation" in team management?', options: ['Doing all the work yourself', 'The assignment of responsibility for tasks to another person', 'Monitoring team performance', 'Setting team goals'], correctAnswer: 'The assignment of responsibility for tasks to another person' },
    { text: 'What is a "SMART" goal?', options: ['Simple, Measurable, Achievable, Relevant, Time-bound', 'Specific, Measurable, Achievable, Relevant, Time-bound', 'Strategic, Meaningful, Actionable, Realistic, Timely', 'Specific, Motivating, Ambitious, Realistic, Trackable'], correctAnswer: 'Specific, Measurable, Achievable, Relevant, Time-bound' },
    { text: 'What is "constructive feedback"?', options: ['Criticizing an employee in front of others', 'Feedback that is specific, actionable, and intended to help the employee improve', 'Ignoring poor performance', 'Praising an employee for everything'], correctAnswer: 'Feedback that is specific, actionable, and intended to help the employee improve' },
    { text: 'What is a key aspect of building a successful team?', options: ['Hiring people who all think the same way', 'Fostering a culture of trust and open communication', 'Avoiding team meetings', 'Setting unclear goals'], correctAnswer: 'Fostering a culture of trust and open communication' },
  ],
  'public-speaking': [
    { text: 'What is a common tip for overcoming public speaking anxiety?', options: ['Avoid eye contact', 'Speak as quickly as possible', 'Practice your presentation multiple times', 'Memorize every single word'], correctAnswer: 'Practice your presentation multiple times' },
    { text: 'What is the "power pose" in the context of public speaking?', options: ['A way to end a speech', 'Standing in a posture of confidence to feel more confident', 'A type of microphone stand', 'A slide design'], correctAnswer: 'Standing in a posture of confidence to feel more confident' },
    { text: 'What is a good way to engage the audience during a presentation?', options: ['Read directly from your slides', 'Ask rhetorical questions and tell relevant stories', 'Avoid using any visuals', 'Speak in a monotone voice'], correctAnswer: 'Ask rhetorical questions and tell relevant stories' },
    { text: 'What is the "10-20-30 Rule" for presentations (popularized by Guy Kawasaki)?', options: ['10 slides, 20 minutes, 30-point font', '10 minutes, 20 slides, 30 words per slide', '10 topics, 20 images, 30 minutes', '10 questions, 20 answers, 30 minutes'], correctAnswer: '10 slides, 20 minutes, 30-point font' },
  ],
  'problem-solving': [
    { text: 'What is the first step in a structured problem-solving process?', options: ['Brainstorming solutions', 'Implementing a solution', 'Defining the problem', 'Evaluating the results'], correctAnswer: 'Defining the problem' },
    { text: 'What is "root cause analysis"?', options: ['A method of problem solving used for identifying the root causes of faults or problems', 'Blaming an individual for a problem', 'A quick fix for a problem', 'Ignoring the problem'], correctAnswer: 'A method of problem solving used for identifying the root causes of faults or problems' },
    { text: 'What is the "5 Whys" technique?', options: ['A technique to brainstorm five solutions', 'An interrogative technique used to explore the cause-and-effect relationships underlying a particular problem', 'A way to prioritize problems', 'A project management framework'], correctAnswer: 'An interrogative technique used to explore the cause-and-effect relationships underlying a particular problem' },
    { text: 'What is "brainstorming"?', options: ['A method for generating ideas to solve a problem', 'A way to criticize ideas', 'A formal decision-making process', 'A way to assign tasks'], correctAnswer: 'A method for generating ideas to solve a problem' },
  ],
  'critical-thinking': [
    { text: 'What is a key aspect of critical thinking?', options: ['Accepting information at face value', 'The objective analysis and evaluation of an issue in order to form a judgment', 'Following your intuition', 'Agreeing with the majority'], correctAnswer: 'The objective analysis and evaluation of an issue in order to form a judgment' },
    { text: 'What is "confirmation bias"?', options: ['The tendency to seek out information that confirms one\'s existing beliefs', 'The ability to think logically', 'A method of solving problems', 'A type of logical fallacy'], correctAnswer: 'The tendency to seek out information that confirms one\'s existing beliefs' },
    { text: 'What is a "logical fallacy"?', options: ['A correct and valid argument', 'A flaw in reasoning that renders an argument invalid', 'A type of evidence', 'A scientific theory'], correctAnswer: 'A flaw in reasoning that renders an argument invalid' },
    { text: 'What does it mean to "play devil\'s advocate"?', options: ['To be disruptive in a discussion', 'To argue against a position for the sake of exploring its weaknesses', 'To end a debate', 'To agree with everyone'], correctAnswer: 'To argue against a position for the sake of exploring its weaknesses' },
  ],
};